## runs gradle wrapper task and creates a PR

name: Upgrade Gradle

on:
  push:
    branches: [ master ]

  schedule:
    - cron: 0 2 * * 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          LATEST_VER=$(curl https://api.github.com/repos/gradle/gradle/releases/latest | jq -r .name)
          ./gradlew wrapper --gradle-version ${LATEST_VER} --distribution-type all
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: "[gradle-updater] updating gradle wrapper to latest version"
          title: "Upgrade Gradle"
